### ISSUE TITLE
path for pubspec.yaml

### ISSUE THREAD

**Issue by elmalote** [Oleksandr32/flutter-QuickPay#1]
Hi

Your example is not complete, what path should be used for the pubspec.yaml and what should it refer to?

quick_pay:
    path: ../ 

is not valid.

Thanks

**Comment by Oleksandr32** [comment]
@elmalote Hi

If you want to use this plugin in your project just add to your `pubspec.yaml` file a line `quick_pay: ^1.0.1` below `dependencies:`.
That's mean that plugin will installed to your project from dart pub.

Please read https://pub.dev/packages/quick_pay/install here.

**Comment by Oleksandr32** [comment]
I will close this issues.
