### ISSUE TITLE
Execution failed for task ':quick_pay:bundleDebugAar'.

### ISSUE THREAD

**Issue by AndreasLyngholm** [Oleksandr32/flutter-QuickPay#2]
When I try to pull in your package, I get the following error:

* What went wrong:
Execution failed for task ':quick_pay:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :quick_pay project caused this error: C:\Users\lyngh\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\quick_pay-1.0.0\android\libs\QuickPaySDK.aar

Is this something you have seen before?

**Comment by Oleksandr32** [comment]
@AndreasLyngholm 

Sorry for delay, please put here example of how you install and use this plugin.
What version of Flutter and Dart do you use?

**Comment by AndreasLyngholm** [comment]
That's all good!

Versions:
Flutter 2.0.6
Dart 2.12.3

I'm following the installing guide from the https://pub.dev/packages/quick_pay/install site.

flutter pub add quick_pay

It pull correctly, but when I try to compile the app and run it, I get the error above.

**Comment by Oleksandr32** [comment]
@AndreasLyngholm 

I have reproduced this issue. 
It looks like that problem in flutter 2.0

I will try another way to put .aar file in plugin

**Comment by AndreasLyngholm** [comment]
Thank you very much!

I really appreciate it.

I am looking forward to an update and to test it out!

**Comment by AndreasLyngholm** [comment]
Hi, do you have a timeframe on this issue?

**Comment by Oleksandr32** [comment]
@AndreasLyngholm 

Hi, unfortunately I have a problems with Flutter 2.0.
So I can only offer you a workaround for that now.

You need to do such steps:
1) Download plugin manually from my github

![image](https://user-images.githubusercontent.com/24620659/119555912-0ff78580-bda7-11eb-9e1a-b19dfdb0e040.png)


2) Unzip and rename folder to `flutter-QuickPay`

3) Create folder `packages` in your root flutter project folder (if you don't have) and copy here `flutter-QuickPay` folder.

![image](https://user-images.githubusercontent.com/24620659/119556378-98762600-bda7-11eb-912e-c8d38b6d5a76.png)


4) Open `settings.gradle` file from `root/android/` folder and add to the top a line 

`apply from: '../packages/flutter-QuickPay/settings.gradle'`

![image](https://user-images.githubusercontent.com/24620659/119556985-55688280-bda8-11eb-81b8-1e5d59b0809d.png)

5) and finally open `pubspec.yaml` file and replace line `quick_pay: ^1.0.1` to 
```
quick_pay: 
  path: ./packages/flutter-QuickPay
```

![image](https://user-images.githubusercontent.com/24620659/119557597-0ec75800-bda9-11eb-91e9-759ebaff90b4.png)



@AndreasLyngholm  Please notify me if you have a problem or if this workaround works good in your project.

**Comment by Oleksandr32** [comment]
@AndreasLyngholm did you try this workaround ?

**Comment by AndreasLyngholm** [comment]
Hi, I had some issues and have been busy. I will give it a try tonight!

I apologize for the lack of response.
